name: frhodo
channels:
  - cantera/label/dev
  - conda-forge
  - defaults
dependencies:
  - cantera=2.5.0b1
  - matplotlib=3.3.1
  - nlopt=2.6.1
  - numpy=1.19.1
  - pyside2=5.13.1
  - qtpy=1.9.0
  - requests=2.24.0
  - scipy=1.5.2
  - tabulate=0.8.7